from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Finding:
    file: str
    line: int
    category: str
    action: str
    code: str


# Order matters: specific patterns must be checked before generic ones.
PATTERNS = [
    (
        re.compile(r"\.cuda\s*\("),
        "Device placement",
        "Adapt",
    ),
    (
        re.compile(r'torch\.device\s*\(\s*["\']cuda'),
        "Device placement",
        "Adapt",
    ),
    (
        re.compile(r'device\s*=\s*["\']cuda'),
        "Device placement",
        "Adapt",
    ),
    (
        re.compile(r'to\s*\(\s*["\']cuda'),
        "Device placement",
        "Adapt",
    ),
    (
        re.compile(
            r"torch\.cuda\.(empty_cache|synchronize|memory_allocated|"
            r"memory_reserved|max_memory_allocated|max_memory_reserved)"
        ),
        "CUDA utility",
        "Investigate",
    ),
    (
        re.compile(r"GradScaler"),
        "AMP",
        "Investigate",
    ),
    (
        re.compile(r"autocast"),
        "AMP",
        "Investigate",
    ),
    (
        re.compile(r"torch\.cuda\.amp"),
        "AMP",
        "Investigate",
    ),
    (
        re.compile(r"\bamp\b", re.IGNORECASE),
        "AMP",
        "Review",
    ),
    (
        re.compile(r"\bnccl\b", re.IGNORECASE),
        "Distributed",
        "Investigate",
    ),
    (
        re.compile(r"torch\.distributed"),
        "Distributed",
        "Investigate",
    ),
    (
        re.compile(r"\blocal_rank\b"),
        "Distributed",
        "Investigate",
    ),
    (
        re.compile(r"\bbf16\b", re.IGNORECASE),
        "Precision",
        "Investigate",
    ),
    (
        re.compile(r"\bfp16\b", re.IGNORECASE),
        "Precision",
        "Investigate",
    ),
    (
        re.compile(r"torch\.cuda"),
        "CUDA reference",
        "Review",
    ),
    (
        re.compile(r"\bcuda\b", re.IGNORECASE),
        "CUDA reference",
        "Review",
    ),
]


DEFAULT_TARGETS = [
    "trainer",
    "scripts",
    "model",
    "eval_llm.py",
]

EXCLUDED_DIRS = {
    ".git",
    ".idea",
    ".venv",
    ".venv-clean",
    "__pycache__",
    "docs/original",
}


def is_excluded(path: Path, root: Path) -> bool:
    relative = path.relative_to(root).as_posix()

    for excluded in EXCLUDED_DIRS:
        if relative == excluded or relative.startswith(f"{excluded}/"):
            return True

    return False


def classify_line(line: str) -> tuple[str, str] | None:
    stripped = line.strip()

    if not stripped:
        return None

    # Keep comments visible but avoid treating them as real implementation issues.
    if stripped.startswith("#"):
        if "cuda" in stripped.lower():
            return "Comment / documentation", "Review"
        return None

    for pattern, category, action in PATTERNS:
        if pattern.search(line):
            return category, action

    return None


def scan_file(path: Path, root: Path) -> list[Finding]:
    findings = []

    try:
        content = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        content = path.read_text(encoding="utf-8", errors="ignore")

    for line_number, line in enumerate(content.splitlines(), start=1):
        result = classify_line(line)

        if result is None:
            continue

        category, action = result

        findings.append(
            Finding(
                file=path.relative_to(root).as_posix(),
                line=line_number,
                category=category,
                action=action,
                code=line.strip(),
            )
        )

    return findings


def collect_python_files(root: Path, targets: list[str]) -> list[Path]:
    files: set[Path] = set()

    for target_name in targets:
        target = root / target_name

        if not target.exists():
            continue

        if target.is_file() and target.suffix == ".py":
            files.add(target)
            continue

        if target.is_dir():
            for path in target.rglob("*.py"):
                if path.name == "audit_directml.py":
                    continue
                
                if not is_excluded(path, root):
                    files.add(path)

    return sorted(files)


def escape_markdown(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace("|", "\\|")
        .replace("`", "\\`")
    )


def generate_report(findings: list[Finding]) -> str:
    lines = [
        "# DirectML Compatibility Audit",
        "",
        "Automatically generated by `scripts/audit_directml.py`.",
        "",
        "> This report identifies potential CUDA-specific code. "
        "Each occurrence must still be reviewed manually before modification.",
        "",
        "## Summary",
        "",
        f"Total findings: **{len(findings)}**",
        "",
    ]

    if findings:
        counts: dict[str, int] = {}

        for finding in findings:
            counts[finding.category] = counts.get(finding.category, 0) + 1

        lines.extend(
            [
                "| Category | Count |",
                "|---|---:|",
            ]
        )

        for category, count in sorted(counts.items()):
            lines.append(f"| {category} | {count} |")

        lines.extend(
            [
                "",
                "## Findings",
                "",
                "| File | Line | Type | Action | Code |",
                "|---|---:|---|---|---|",
            ]
        )

        for finding in findings:
            code = escape_markdown(finding.code)

            lines.append(
                f"| `{finding.file}` "
                f"| {finding.line} "
                f"| {finding.category} "
                f"| {finding.action} "
                f"| `{code}` |"
            )
    else:
        lines.extend(
            [
                "No CUDA or DirectML-sensitive code was detected.",
                "",
            ]
        )

    lines.extend(
        [
            "",
            "## Action meanings",
            "",
            "- **Adapt** — expected to require a DirectML-compatible implementation.",
            "- **Investigate** — behavior or DirectML support must be tested before changing it.",
            "- **Review** — inspect manually; the occurrence may be harmless.",
            "",
            "## Recommended review order",
            "",
            "1. Device placement",
            "2. CUDA utilities",
            "3. AMP / mixed precision",
            "4. Distributed training",
            "5. Precision options",
            "6. Generic CUDA references",
            "",
        ]
    )

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Audit MiniMind source code for CUDA-specific constructs."
    )

    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root directory.",
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output Markdown file.",
    )

    args = parser.parse_args()

    root = args.root.resolve()

    output = (
        args.output.resolve()
        if args.output
        else root / "docs" / "directml_audit.md"
    )

    python_files = collect_python_files(root, DEFAULT_TARGETS)

    findings = []

    for path in python_files:
        findings.extend(scan_file(path, root))

    findings.sort(key=lambda item: (item.file, item.line))

    report = generate_report(findings)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report, encoding="utf-8")

    print("DirectML audit completed.")
    print(f"Files scanned: {len(python_files)}")
    print(f"Findings: {len(findings)}")
    print(f"Report: {output.relative_to(root)}")


if __name__ == "__main__":
    main()